[workspace]
resolver = "2"
members = [
    "embedded-line-edit",
    "krabby"
, "page-alloc"]

# Printing the device tree without optimizations overruns the stack
[profile.dev.package.fdt]
opt-level = 3

[profile.release]
lto = "thin"
strip = true
