[package]
name = "krabby"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib","lib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0.84"
