[package]
name = "krabby"
version = "0.0.0"
edition = "2021"
rust-version = "1.74"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owo-colors = "3.5.0"

[build-dependencies]
cc = "1.0.84"
