[package]
name = "gary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kanto = { version = "0.0.0", path = "../kanto" }
