---
name: Build

# yamllint disable-line rule:truthy
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: ./install-dependencies.sh --ci

      - name: Build
        run: cargo build

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Lint
        run: cargo fmt --check
