---
name: Build

# yamllint disable-line rule:truthy
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: ./install-dependencies.sh --ci

      - name: Build
        run: cargo build

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Clippy (userspace)
        run: cd userspace && cargo clippy -- -D warnings

      - name: Lint
        run: cargo fmt --check

      - name: Lint (userspace)
        run: cd userspace && cargo fmt --check

      - name: Check docs
        run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps

      - name: Test kernel
        run: timeout 60 cargo run --features=test

      - name: Test line edit crate
        run: cd embedded-line-edit && cargo test

      - name: Test page-alloc crate
        run: cd page-alloc && cargo test
